version: "3"
services:
  postgres_db:
    image: "postgres:12"
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: "evraz"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"

  api_service:
    build: .
    restart: always
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL_DB: jdbc:postgresql://postgres_db:5432/evraz
      SPRING_DATASOURCE_USERNAME_DB: root
      SPRING_DATASOURCE_PASSWORD_DB: root
      JAVA_OPTS: -Djavax.net.ssl.trustStore=/certs/CA.pem -Djavax.net.ssl.trustStorePassword=changeit

    depends_on:
      - postgres_db

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper